@startuml
hide circle
skinparam linetype ortho

entity "ユーザ" as user {
  +id : int(10)
  --
  name : varchar(255)
  *email : varchar(255)
  email_verified_at : timestamp
  password : varchar(255)
  remember_token : varchar(100)
  role : tinyint
  delete_flag : tinyint
  created_at : timestamp
  updated_at : timestamp
}

entity "勤怠" as attendance {
  +id : int
  --
  #user_id : int [FK(user,id)]
  *work_date : DATE
  *work_division_id : int <<FK>>
  attendance_time : DATETIME
  departure_time : DATETIME
  break_time : TIME
  work_time : TIME
  create_user_id :int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "勤怠設定" as attendance_propaty {
    +id : int
    --
    department_id : int
    work_time_start : TIME
    work_time_end : TIME
    break_time_start : TIME
    break_time_end : TIME
    create_user_id : int
    created_at : timestamp
    update_user_id : int
    updated_at : timestamp
}

entity "勤怠区分" as work_division {
  +id : int
  --
  division_name : varchar(255)
  created_at : timestamp
  updated_at : timestamp
}

entity "スタッフ" as staff {
  +id : int
  --
  user_id : int
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "組織" as department {
  +id : int
  --
  user_id : int <<FK>>
  name : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "権限" as role {
  +id : int
  --
  description : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

user||--o{attendance
user||--||staff
user||--|{department
user }o--||role
department||--o{staff
department||--||attendance_propaty
work_division||--o{attendance

@enduml
