@startuml
hide circle
skinparam linetype ortho

entity "ユーザ" as user {
  +id : int(10)
  --
  name : varchar(255)
  email : varchar(255)
  email_verified_at : timestamp
  password : varchar(255)
  remember_token : varchar(100)
  role : tinyint
  delete_flag : tinyint
  created_at : timestamp
  updated_at : timestamp
}

entity "勤怠設定" as attendance_property {
    +id : int
    --
    department_id : int
    work_time_start : TIME
    work_time_end : TIME
    break_time_start : TIME
    break_time_end : TIME
    create_user_id : int
    created_at : timestamp
    update_user_id : int
    updated_at : timestamp
}

entity "勤怠区分" as work_division {
  +id : int
  --
  division_name : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "打刻タイプ" as dakoku_type {
  +id : int
  --
  type : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "スタッフ" as staff {
  +id : int
  --
  user_id : int
  department_id : int
  delete_flag : tinyint
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "組織" as departments {
  +id : int
  --
  user_id : int <<FK>>
  name : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "権限" as role {
  +id : int
  --
  description : varchar(255)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "タイムカード" as timecards {
  +id : int
  --
  staff_id : int
  ymd : char(8)
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "日別打刻情報" as daily_dakoku {
  +id : int
  --
  timecard_id : int
  work_type : int
  del_flg : tinyint
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

entity "日別打刻情報" as dakoku_time {
  +id : int
  --
  daily_dakoku_id : int
  dakoku_type : int
  del_flg : tinyint
  time : datetime
  create_user_id : int
  created_at : timestamp
  update_user_id : int
  updated_at : timestamp
}

user||--|{departments
user ||-l-||role
departments ||--o{ staff
departments ||-l-||attendance_property
staff||--o{timecards
timecards ||--o{daily_dakoku
daily_dakoku ||-l-|| work_division
daily_dakoku ||--o{ dakoku_time
dakoku_time ||-l-|| dakoku_type
@enduml
