```plantuml
@startuml

hide circle
hide method

package すり合わせ設定 {

    class すり合わせ設定{
        すり合わせ設定ID
        評価期間
        タイトル
        作成者
        作成日時
        更新者
        更新日時
    }

    class ステータス{
    }

    class すり合わせ種類{
    }
}

note top of すり合わせ設定
    すり合わせ種類は[管理職すり合わせ/評価者すり合わせ]
    ステータスは[一時保存/データ作成中/作成失敗/登録済み/削除/終了]
    ステータスは一時保存で最初に作成される
end note

package 参加者 {

    class 参加者リスト{
    }

    class 参加者 {
        ID
        すり合わせ設定ID
        社員ID
        作成者
        更新者
    }
}

note left of 参加者
    一般以下は参加者になることはできない
    管理職すり合わせの場合は管理職しか参加者になることはできない
end note

package 評価対象者 {

    class 評価対象者リスト{
    }

    class 評価対象者 {
        ID
        すり合わせ設定ID
        社員ID
        作成者
        更新者
    }
}

package 管理者 {

    class 管理者リスト {
        すり合わせ設定ID
    }

    class 管理者 {
        ID
        社員ID
    }
}

note top of 管理者リスト
    すり合わせ設定を変更できるのは,
    すり合わせ管理者のみ
    すり合わせ作成者はデフォルトで管理者とし、
    削除することはできない
    設定編集中のユーザは自身を管理者から
    削除することはできない
end note

note top of 管理者
    すり合わせ管理者としての条件
    評価者すり合わせ→上位評価者,管理職
    管理職すり合わせ→管理職
end note

package 社員情報 {
     class 社員情報 {
        社員ID
        SkyID
        名字
        名前
     }

     class 役職 {
        役職ID
        役職名
        役職省略名
        役職レベル
        管理職フラグ
        表示順
     }

     class 事業部 {
        事業部ID
        事業務名
        事業部略称
        並び順
     }

     class 部署 {
        部署ID
        部署名
        部署略称
        並び順
     }

     class チーム {
        チームID
        チーム名
        チーム略称
        並び順
     }
}

package タブ {
    class タブ {
        タブID
        タブ名称
        並び順
    }
}

package すり合わせタブ {

    class すり合わせタブリスト{
    }

    class すり合わせタブ {
        すり合わせタブID
        すり合わせ設定ID
        タブID
        タブ名称
        並び順
        作成者
        更新者
    }
}

note top of すり合わせタブリスト
    タブは追加できる
    追加タブは削除できる
end note

package すり合わせ項目 {
    class すり合わせ項目 {
        すり合わせ項目ID
        すり合わせ設定ID
        項目ID
        項目名
        管理職項目フラグ
        任意項目フラグ
    }
}

note left of すり合わせ項目
    評価者すり合わせの場合、
    管理職項目フラグの立っている項目は閲覧できない
end note

package すり合わせ任意項目 {
    class すり合わせ任意項目 {
        ID
        すり合わせ項目ID
        社員ID
        値
    }
}

note bottom of すり合わせ任意項目
    任意項目は追加できる
end note

package すり合わせ表示項目 {
    class すり合わせ表示項目 {
        ID
        すり合わせ設定ID
        すり合わせタブID
        すり合わせ項目ID
    }
}

package すり合わせ選択可能項目 {
    class すり合わせ選択可能項目{
        ID
        すり合わせ設定ID
        すり合わせタブID
        すり合わせ項目ID
    }
}

package すり合わせ会議タブ {
    class すり合わせ会議タブ {
        すり合わせ設定ID
        すり合わせタブID
        タブ名
        タブNo
    }
}

package すり合わせ会議項目 {
    class すり合わせ会議項目 {
        すり合わせ項目ID
        項目名
        項目No
    }
}

package すり合わせ会議値 {
    class すり合わせ会議値 {
        すり合わせ会議ID
        すり合わせ項目ID
        社員ID
        値
    }
}

package 管理職査定{

    class 査定{
    }

    class 管理職すり合わせ査定{
    }

    class 評価者すり合わせ査定

    class 管理職すり合わせ{
        管理職すり合わせ
        役職フラグ
        アラート
        すり合わせ実役職
    }

    class 部内すり合わせ{
    }

    class 査定ステータス{
    }

    class 役職フラグ{
    }

    class 表彰{
        表彰ID
        表彰No
    }

    class イエロー{
    }

    class 抜擢{
    }
}

note top of 査定
    ・提出済み場合は更新不可
    ・反映は常に一時保存状態にするだけ
    ・評価者すり合わせの場合は管理職すり合わせ用の
    　項目は閲覧・変更できない
    ・反映時には対象者のすり合わせ会議値を作り直し、
    　表示にも反映させる
    ・査定更新時には更新前査定と比較する
end note

package 昇格率 {
    class 昇格率計算情報 {
        役職フラグID
        性別
        実役職レベル
        すり合わせ実役職レベル
    }

    class 昇格率計算{
        トータル人数取得():int
        昇格率取得():int
        降格率取得():int
        女性昇格率取得():int
    }

    class 役職レベル{
    }

    class 性別{
    }

    class 役職フラグ1{
    }
}

note top of 昇格率計算
    昇格/降格等の情報をリストとして計算する
end note

note bottom of 昇格率計算情報
    [昇格定義]
    役職フラグが上の人
    [降格定義]
    すり合わせ実役職が実役職より下がっていいる人
end note

package 共有メモ{
    class 共有メモ{
        評価ID
        共有コメント
        更新時間
    }
}

note top of 共有メモ
    取得後に他の人に更新された場合は、更新できない
end note

package すり合わせURL {
    class すり合わせURLリスト {
        すり合わせ設定ID
    }

    class すり合わせURL {
        評価者すり合わせURL_ID
        すり合わせ設定ID
        発行URL
        対象役職レベル
    }
}

note top of すり合わせURLリスト
    ・一般以下の場合は同一のURLとする
    ・自身より下の役職全てが閲覧できるURLを必ず発行する
end note

note bottom of すり合わせURL
    ・一般より上は各役職層毎にランダムなURLを発行する
end note

package 営業期区分 {
    class 営業期区分 {
        営業期区分ID
    }
}

note top of 営業期区分
    【春秋】
     昇格査定
    【夏冬】
     賞与査定
end note

package 営業期 {
    class 営業期 {
        営業期ID
    }
}

すり合わせ設定 *-left- ステータス
すり合わせ設定 *-left- すり合わせ種類
すり合わせ設定 -down-> 管理者リスト
すり合わせ設定 -down-> 参加者リスト
すり合わせ設定 -down-> 評価対象者リスト
すり合わせ設定 --down-> すり合わせタブリスト
すり合わせ設定 --right-> すり合わせ会議タブ
すり合わせ設定 --right-> すり合わせ会議項目
すり合わせ設定 --right-> すり合わせ会議値
すり合わせ設定 --right-> すり合わせURLリスト

管理者リスト *-down-|{ 管理者
管理者 -down-> 社員情報
参加者リスト *-down-|{ 参加者
参加者 -down-> 社員情報
評価対象者リスト *-down-|{ 評価対象者
評価対象者 -down-> 社員情報

社員情報 *-down- 役職
社員情報 *-down- 事業部
社員情報 *-down- 部署
社員情報 *-down- チーム

すり合わせタブリスト *--|{ すり合わせタブ
すり合わせタブ -down-> タブ
すり合わせタブ -down-> すり合わせ選択可能項目
すり合わせタブ -down-> すり合わせ表示項目

すり合わせ項目 -down-> すり合わせ任意項目
すり合わせ表示項目 -down-> すり合わせ項目
すり合わせ選択可能項目 -down-> すり合わせ項目

昇格率計算 *-down-|{ 昇格率計算情報
昇格率計算情報 *-down- 役職レベル
昇格率計算情報 *-down- 性別
昇格率計算情報 *-down- 役職フラグ1

すり合わせURLリスト *-down-|{ すり合わせURL

査定 <|-down- 管理職すり合わせ査定
査定 <|-down- 評価者すり合わせ査定
管理職すり合わせ査定 *-down- 査定ステータス
評価者すり合わせ査定 *-down- 査定ステータス
管理職すり合わせ査定 *-down- 表彰
評価者すり合わせ査定 *-down- 表彰
管理職すり合わせ査定 *-down- 役職フラグ
管理職すり合わせ査定 *-down- イエロー
管理職すり合わせ査定 *-down- 抜擢
管理職すり合わせ査定 *-down- 管理職すり合わせ
評価者すり合わせ査定 *-down- 部内すり合わせ


@enduml
```
