@startuml suriawaseProject
skinparam PackageStyle rectangle

package すり合わせ設定集約 {
    object すり合わせ設定 {
        すり合わせ設定ID
        すり合わせタイトル
        すり合わせ種類
        ステータス
    }
}

note left of すり合わせ設定
    すり合わせ種類は[管理職すり合わせ/評価者すり合わせ]
    ステータスは[一時保存/データ作成中/作成失敗/登録済み/削除/終了]
    ステータスは一時保存で最初に作成される
end note

package 管理者集約 {
    object 管理者 {
        すり合わせ設定ID
        社員ID
        役職レベル
        管理者フラグ
    }
}

note left of 管理者
    すり合わせ設定を変更できるのはすり合わせ管理者のみ
    すり合わせ管理者になれるのは、
    評価者すり合わせ→上位評価者,管理職
    管理職すり合わせ→管理職
    すり合わせ作成者はデフォルトで管理者とする
end note

package 参加者集約 {
    object 参加者{
        すり合わせ設計ID
        社員ID
        役職レベル
        管理者フラグ
    }
}

note right of 参加者
    一般以下は参加者になることはできない
    管理職すり合わせの場合は管理職しか参加者になることはできない
end note

package 評価対象者集約 {
    object 評価対象者{
        すり合わせ設計ID
        社員ID
        役職レベル
        管理者フラグ
    }
}

package 査定参考表示項目集約 {

    object タブ{
        すり合わせ設定ID
        タブNo
        追加フラグ
    }

    object 表示項目{
        表示項目ID
        必須フラグ
        並び順
    }

    object 選択可能項目{
        選択可能項目ID
        並び順
    }
}

note right of タブ
    タブは追加できる
    追加タブは削除できる
end note

package 項目集約 {
    object 項目 {
        項目ID
        項目名称
        管理職フラグ
        任意項目フラグ
    }
}

note right of 項目
    任意項目を追加できる
end note

すり合わせ設定 "1" -down-> "0..n" 管理者
すり合わせ設定 "1" -down-> "0..n" 参加者
すり合わせ設定 "1" -down-> "0..n" 評価対象者
すり合わせ設定 "1" -right-> "0..n" タブ

タブ "1" *-down- "0..n" 表示項目
タブ "1" *-down- "0..n" 選択可能項目
表示項目 "1" -down-> "1" 項目
選択可能項目 "1" -down-> "1" 項目

@enduml
