```plantuml
@startuml

package すり合わせ{
    package すり合わせ設定 {

        class すり合わせ設定{
            すり合わせ設定ID
            評価期間
            タイトル
            作成者
            作成日時
            更新者
            更新日時
            作成者かどうか(int SKyId):bool
        }

        enum ステータス{
        }

        enum すり合わせ種類{
        }
    }

    note top of すり合わせ設定
        すり合わせ種類は[管理職すり合わせ/評価者すり合わせ]
        ステータスは[一時保存/データ作成中/作成失敗/登録済み/削除/終了]
        ステータスは一時保存で最初に作成される
    end note

    package 参加者 {

        class 参加者リスト{
        }

        class 参加者 {
            ID
            すり合わせ設定ID
            社員ID
            作成者
            更新者
        }
    }

    note left of 参加者
        一般以下は参加者になることはできない
        管理職すり合わせの場合は管理職しか参加者になることはできない
    end note

    package 評価対象者 {

        class 評価対象者リスト{
        }

        class 評価対象者 {
            ID
            すり合わせ設定ID
            社員ID
            作成者
            更新者
        }
    }

    package 管理者 {

        class 管理者リスト {
            すり合わせ設定ID
            存在するか():bool
            追加済みかどうか(int 社員ID):bool
            管理者かどうか(LoginuUesrInfo):bool
            追加(社員情報リスト、すり合わせ設定):void
            削除可能検証(社員情報リスト、すり合わせ設定):void
        }

        class 管理者 {
            ID
            社員ID
        }

        class 管理者リポジトリ{
            管理者リスト取得(すり合わせ設定):管理者リスト
        }

        class 管理者仕様草案{
            削除可能かどうか(社員情報,LoginUserInfo,すり合わせ設定):bool
            管理者条件を満たしているかどうか(社員情報,すり合わせ種類):bool
        }
    }

    note top of 管理者リスト
        すり合わせ設定を変更できるのは,
        すり合わせ管理者のみ
        すり合わせ作成者はデフォルトで管理者とし、
        削除することはできない
    end note

    note bottom of 管理者
        すり合わせ管理者としての条件
        評価者すり合わせ→上位評価者,管理職
        管理職すり合わせ→管理職
    end note

    package 社員情報 {
         class 社員情報 {
            社員ID
            SkyID
            名字
            名前
         }

         class 役職 {
            役職ID
            役職名
            役職省略名
            役職レベル
            管理職フラグ
            表示順
         }

         class 事業部 {
            事業部ID
            事業務名
            事業部略称
            並び順
         }

         class 部署 {
            部署ID
            部署名
            部署略称
            並び順
         }

         class チーム {
            チームID
            チーム名
            チーム略称
            並び順
         }
    }

    package タブ {
        class タブ {
            タブID
            タブ名称
            並び順
        }
    }

    package すり合わせタブ {

        class すり合わせタブリスト{
        }

        class すり合わせタブ {
            すり合わせタブID
            すり合わせ設定ID
            タブID
            タブ名称
            並び順
            作成者
            更新者
        }
    }

    note top of すり合わせタブリスト
        タブは追加できる
        追加タブは削除できる
    end note

    package すり合わせ項目 {
        class すり合わせ項目 {
            すり合わせ項目ID
            すり合わせ設定ID
            項目ID
            項目名
            任意項目フラグ
        }
    }

    package すり合わせ任意項目 {
        class すり合わせ任意項目 {
            ID
            社員ID
            値
        }
    }

    package すり合わせ表示項目 {
        class すり合わせ表示項目 {
            ID
            すり合わせ設定ID
            すり合わせタブID
            すり合わせ項目ID
        }
    }

    package すり合わせ選択可能項目 {
        class すり合わせ選択可能項目{
            ID
            すり合わせ設定ID
            すり合わせタブID
            すり合わせ項目ID
        }
    }

    package すり合わせ会議タブ {
        class すり合わせ会議タブ {
            すり合わせ設定ID
            すり合わせタブID
            タブ名
            タブNo
        }
    }

    package すり合わせ会議項目 {
        class すり合わせ会議項目 {
            すり合わせ項目ID
            項目名
            項目No
        }
    }


    package すり合わせ会議値 {
        class すり合わせ会議値 {
            行数
            すり合わせ会議ID
            すり合わせ項目ID
            社員ID
            値
        }
    }

    package すり合わせURL {

         class すり合わせURL {
             -すり合わせURL_ID
             -発行URL
             -対象役職レベル
             URL発行():void
             一般以下の対象役職レベルかどうか():void
         }

         class すり合わせURLリスト {
             -すり合わせ設定ID
             一般以下URLが存在しているか():bool
             全表示用すり合わせURL生成():void
             追加(int[] 役職レベルリスト):void
         }
    }
}

package 昇格率 {

    class 計算リードクエリ(別案){
        SQLで集計もできるが、
        拡張性とか業務ロジックがかなり入る
    }

    class 昇格率計算リポジトリ{
        表示対象者(すり合わせ設定):昇格率計算
        事業部(事業部ID,営業期):昇格率計算
        部署取得(部署ID,営業期):昇格率計算
    }

    class 昇格率計算情報 {
        -役職フラグID
        -性別
        -実役職レベル
        -すり合わせ実役職レベル
        昇格かどうか():bool
        降格かどうか():bool
    }

    class 昇格率計算{
        トータル人数取得():int
        昇格率取得():int
        降格率取得():int
        女性昇格率取得():int
    }

    class 役職フラグ{
        上かどうか():bool
    }

    class 役職レベル{
        高位役職かどうか():bool
    }

    enum 性別{
        女性かどうか():bool
    }
}

package 共有メモ{
    class 共有メモ{
        評価ID
        共有コメント
        更新時間
        バージョン確認(datetime リクエスト→更新時間):bool
        提出(string コメント):void
    }
}

package 管理職査定{
    class 管理職査定{
    }
}

すり合わせ設定 *-left- ステータス
すり合わせ設定 *-left- すり合わせ種類
すり合わせ設定 -down-> 管理者リスト
すり合わせ設定 -down-> 参加者リスト
すり合わせ設定 -down-> 評価対象者リスト
すり合わせ設定 --down-> すり合わせタブリスト
すり合わせ設定 --right-> すり合わせ会議タブ
すり合わせ設定 --right-> すり合わせ会議項目
すり合わせ設定 --right-> すり合わせ会議値
すり合わせ設定 --right-> すり合わせURLリスト

管理者リスト *-down-|{ 管理者
管理者 -down-> 社員情報
参加者リスト *-down-|{ 参加者
参加者 -down-> 社員情報
評価対象者リスト *-down-|{ 評価対象者
評価対象者 -down-> 社員情報

社員情報 *-down- 役職
社員情報 *-down- 事業部
社員情報 *-down- 部署
社員情報 *-down- チーム

すり合わせタブリスト *--|{ すり合わせタブ
すり合わせタブ -down-> タブ
すり合わせタブ -down-> すり合わせ表示項目
すり合わせタブ -down-> すり合わせ選択可能項目

すり合わせ項目 -down-> すり合わせ任意項目
すり合わせ表示項目 -down-> すり合わせ項目
すり合わせ選択可能項目 -down-> すり合わせ項目

昇格率計算 *-down-|{ 昇格率計算情報
昇格率計算情報 *-down- 役職フラグ
昇格率計算情報 *-down- 役職レベル
昇格率計算情報 *-down- 性別

すり合わせURLリスト *-down-|{ すり合わせURL

@enduml
```
