@startuml suriawaseProject

package すり合わせ設定集約 {
    class すり合わせ設定 {
        - すり合わせ設定ID
        - すり合わせタイトル
        - すり合わせ種類
        - ステータス
        登録():void
        最新化():void
        失敗():void
        削除():void
    }

    class ステータス {
        - ステータス
    }

    class すり合わせ種類 {
        - すり合わせ種類
        評価者すり合わせかどうか():bool
        管理職すり合わせかどうか():bool
    }
}

note left of すり合わせ設定
    すり合わせ種類は[管理職すり合わせ/評価者すり合わせ]
    ステータスは[一時保存/データ作成中/作成失敗/登録済み/削除/終了]
    ステータスは一時保存で最初に作成される
end note

package 管理者集約 {

    class 管理者リスト {
        -すり合わせ設定ID
        +存在するか():bool
        +追加済みかどうか(int 社員ID):bool
        +作成者かどうか():bool
        +管理者かどうか(LoginuUesrInfo):bool
        +追加(参加者、すり合わせ設定):void
        +削除(int 社員ID):void
        +社員IDリスト取得():array
    }

    class 管理者 {
        -社員ID
        -役職レベル
        -管理者フラグ
        +管理者条件を満たしているかどうか(すり合わせ種類):bool
    }
}

note left of 管理者
    すり合わせ設定を変更できるのはすり合わせ管理者のみ
    すり合わせ管理者になれるのは、
    評価者すり合わせ→上位評価者,管理職
    管理職すり合わせ→管理職
    すり合わせ作成者はデフォルトで管理者とし、削除することはできない
end note

package 参加者集約 {

    class 参加者リスト {
        -すり合わせ設定ID
        +存在するか():bool
        +追加(管理者、すり合わせ設定):void
        +削除(int 社員ID):void
        +社員IDリスト取得():array
    }

    class 参加者{
        -すり合わせ設計ID
        -社員ID
        -役職レベル
        -管理者フラグ
        +参加者条件を満たしているかどうか(すり合わせ種類):bool
    }
}

note right of 参加者
    一般以下は参加者になることはできない
    管理職すり合わせの場合は管理職しか参加者になることはできない
end note

package 評価対象者集約 {

    class 評価対象者リスト {
        -すり合わせ設定ID
        +存在するか():bool
        +追加(管理者、すり合わせ設定):void
        +削除(int 社員ID):void
        +社員IDリスト取得():array
    }

    class 評価対象者{
        すり合わせ設計ID
        社員ID
        役職レベル
        管理者フラグ
    }
}

package 査定参考表示項目集約 {

    class タブリスト {
        すり合わせ設定ID
        タブ追加(string タブ名称, タブ):void
        タブ削除(int タブNo):void
        更新(タブNo, array 表示項目情報, array 選択項目情報):void
    }

    class タブ{
        タブNo
        タブ名称
        追加フラグ
        追加タブかどうか():bool
        タブ名称セット():void
        表示項目更新():void
        選択可能項目更新():void
    }

    object 表示項目{
        表示項目ID
        必須フラグ
        並び順
    }

    object 選択可能項目{
        選択可能項目ID
        並び順
    }
}

note right of タブ
    タブは追加できる

    追加タブは削除できる
end note

package 項目集約 {
    object 項目 {
        項目ID
        項目名称
        管理職フラグ
        任意項目フラグ
    }
}

note right of 項目
    任意項目を追加できる
end note

すり合わせ設定 "1" -down-> "1" 管理者リスト
すり合わせ設定 "1" *-down- "1" ステータス
すり合わせ設定 "1" *-down- "1" すり合わせ種類
すり合わせ設定 "1" -down-> "1" 参加者リスト
すり合わせ設定 "1" -down-> "1" 評価対象者リスト
すり合わせ設定 "1" -right-> "1" タブリスト

管理者リスト "1" *-down- "0..n" 管理者
参加者リスト "1" *-down- "0..n" 参加者
評価対象者リスト "1" *-down- "0..n" 評価対象者
タブリスト "1" *-down- "0..n" タブ

タブ "1" *-down- "0..n" 表示項目
タブ "1" *-down- "0..n" 選択可能項目
表示項目 "1" -down-> "1" 項目
選択可能項目 "1" -down-> "1" 項目

@enduml
