@startuml
hide circle
hide methods
left to right direction

package 勤怠管理{

    rectangle 組織集約{
        class 組織
        組織 *-- 勤怠設定
        組織 : ユーザID
        組織 : 名称

        class 勤怠設定
        勤怠設定 : 組織ID
        勤怠設定 : 勤怠開始時間
        勤怠設定 : 勤怠終了時間
        勤怠設定 : 休憩開始時間
        勤怠設定 : 休憩終了時間
    }

    rectangle ユーザ集約{
        class ユーザ{
            名前
            メールアドレス
            パスワード
            ロール
        }
    }

    rectangle スタッフ集約{
        class スタッフ{
            ユーザID
            組織ID
        }
    }

    rectangle 打刻集約{
        class タイムカード{
            スタッフID
            年月日
        }

        class 日別打刻情報{
            タイムカードID
            勤務タイプ
        }

        class 打刻時間{
            日別打刻情報ID
            打刻タイプ
            時間
        }
    }

    class 打刻タイプ{
        打刻タイプ
    }

    class 勤務タイプ{
        勤務タイプ
    }

    ユーザ集約 o-- 組織集約
    組織集約 o-- スタッフ集約
    スタッフ集約 o-- 打刻集約

    タイムカード o-日別打刻情報
    日別打刻情報 o-打刻時間
    日別打刻情報 --> 勤務タイプ
    打刻時間 --> 打刻タイプ

}
@enduml
